COA/urls.py
from django.urls import path
from .views import AccountListView, AccountCreateView,AccountDetailView,AccountUpdateView,AccountDeleteView, export_csv_view,import_csv_view
app_name = 'COA'

urlpatterns = [
    path('accounts/', AccountListView.as_view(), name='account_list'),
    path('accounts/create/', AccountCreateView.as_view(), name='account_create'),
    path('accounts/<int:pk>/', AccountDetailView.as_view(), name='account_detail'),
    path('accounts/<int:pk>/update/', AccountUpdateView.as_view(), name='account_update'),
    path('accounts/<int:pk>/delete/', AccountDeleteView.as_view(), name='account_delete'),
    path('export-csv/', export_csv_view, name='export_csv'),
    path('import-csv/', import_csv_view, name='import_csv'),
]

customer/urls.py
# customers/urls.py

from django.urls import path
from . import views
from .views import export_csv_view

app_name = 'customers'  # Optional: Namespace for URL names

urlpatterns = [
    path('', views.CustomerListView.as_view(), name='customer-list'),
    path('create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('<str:pk>/', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('<str:pk>/update/', views.CustomerUpdateView.as_view(),
         name='customer_update'),
    path('<str:pk>/delete/', views.CustomerDeleteView.as_view(),
         name='customer-delete'),
    path('export-csv/customers/', export_csv_view, name='export-csv'),
    path('filter/', views.FilterCustomersView.as_view(), name='filter'),

]

htktAcct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [

    path("", include("home.urls")),
    path("coa/", include("COA.urls")),
    path("companyinfo/", include("companyinfo.urls")),
    path("product/", include("product.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/password_reset/",
        PasswordResetView.as_view(
            template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "accounts/login/",
        LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path(
        "accounts/loggout/",
        LogoutView.as_view(template_name="registration/logged_out.html"),
        name="logout",
    ),
    path("admin/", admin.site.urls),
    path('customer/', include('customer.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

customer/models.py
from django.db import models
from django.http import HttpResponse
import unicodecsv as csv


class Customer(models.Model):
    """
    Represents a customer (company or similar entity) in the accounting system.
    """

    # Basic information
    name = models.CharField(max_length=255)
    address = models.TextField(blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    # Financial details
    account_balance = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    credit_limit = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)

    # Other relevant fields (you can customize as needed)
    tax_id = models.CharField(
        max_length=20, blank=False, null=False, primary_key=True)
    industry = models.CharField(max_length=100, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    @staticmethod
    def export_to_csv():
        """Retrieves all customers, creates a CSV response, writes headers and data rows, and returns the CSV content.
    """
        customers = Customer.objects.all()
        response = HttpResponse(content_type='text/csv; charset=utf-8')
        response['Content-Disposition'] = 'attachment; filename="customer_data.csv"'

        writer = csv.writer(response, encoding='utf-8-sig')
        writer.writerow([
            'Tax ID', 'Name', 'Address', 'Phone Number', 'Email',
            'Account Balance', 'Credit Limit', 'Industry', 'Notes'
        ])

        for customer in customers:
            writer.writerow([
                customer.tax_id, customer.name, customer.address, customer.phone_number, customer.email,
                customer.account_balance, customer.credit_limit, customer.industry, customer.notes
            ])

        return response

customer/forms.py
# forms.py

from django import forms
from .models import Customer  # Assuming your Customer model is defined in models.py
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'email', 'phone_number',
                  'tax_id']  # Customize fields for update


class CustomerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = [
            'name',
            'address',
            'phone_number',
            'email',
            'account_balance',
            'credit_limit',
            'tax_id',
            'industry',
            'notes',
        ]
        widgets = {
            'notes': SummernoteWidget(),

        }
    # You can customize form widgets, labels, and validation as needed

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Example: Customize widget attributes
        self.fields['account_balance'].widget.attrs.update(
            {'class': 'form-control'})
        # Example: Change field label
        self.fields['tax_id'].label = 'Tax ID'
        # Add any additional customizations here

customer/views.py
# Assuming you have a form for updating customers
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
import csv
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import DeleteView
from .forms import CustomerForm, CustomerUpdateForm
from django.views.generic.edit import UpdateView
from django.views.generic import ListView, DetailView
from django.shortcuts import render

# Create your views here.
from django.views.generic.edit import CreateView
from .models import Customer
from .forms import CustomerForm  # Assuming you have a form for creating customers


def export_csv_view(request):
    return Customer.export_to_csv()


class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customer/customer_form.html'
    success_url = reverse_lazy('customers:customer-list')


class CustomerListView(LoginRequiredMixin, ListView):
    model = Customer
    template_name = 'customer_list.html'
    context_object_name = 'customers'
    paginate_by = 10  # Set the number of customers per page

    def get_queryset(self):
        # Order the queryset by a specific field (e.g., 'last_name')
        return super().get_queryset().order_by('name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        paginator = Paginator(queryset, self.paginate_by)
        # Get the current page number from the URL
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context


class CustomerDetailView(LoginRequiredMixin, DetailView):
    model = Customer
    template_name = 'customer/customer_detail.html'
    context_object_name = 'customer'


class CustomerUpdateView(LoginRequiredMixin, UpdateView):
    model = Customer
    form_class = CustomerUpdateForm
    template_name = 'customer/customer_update_form.html'
    success_url = reverse_lazy('customers:customer-list')


class CustomerDeleteView(LoginRequiredMixin, DeleteView):
    model = Customer
    template_name = 'customer/customer_confirm_delete.html'
    # Redirect to the customer list page
    success_url = reverse_lazy('customers:customer-list')


class FilterCustomersView(View):
    def get(self, request, *args, **kwargs):
        q = request.GET.get('q', '')
        customers = Customer.objects.filter(name__icontains=q)
        customer_list = serializers.serialize('json', customers)
        return JsonResponse(customer_list, safe=False)

templates/customer/customer_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mt-5">Delete Customer</h1>
            <p>Are you sure you want to delete the customer "{{ customer.name }}"?</p>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger"> {% translate 'Yes, delete' %} </button>
            </form>
            <a href="{% url 'customers:customer-list' %}" class="btn btn-primary mt-3">{% trans 'No, take me back' %}
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/customer/customer_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
Customer Detail
{% endblock title %}

{% block content %}
<div class="container py-5">
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h2 class="mb-0">Customer Detail</h2>
        </div>
        <div class="card-body">
            <p><strong class="text-primary">Name:</strong> {{ customer.name }}</p>
            <p><strong class="text-primary">Address:</strong> {{ customer.address }}</p>
            <p><strong class="text-primary">Phone Number:</strong> {{ customer.phone_number }}</p>
            <p><strong class="text-primary">Email:</strong> {{ customer.email }}</p>
            <p><strong class="text-primary">Account Balance:</strong> {{ customer.account_balance }}</p>
            <p><strong class="text-primary">Credit Limit:</strong> {{ customer.credit_limit }}</p>
            <p><strong class="text-primary">Tax ID:</strong> {{ customer.tax_id }}</p>
            <p><strong class="text-primary">Industry:</strong> {{ customer.industry }}</p>
            <p><strong class="text-primary">Notes:</strong> {{ customer.notes }}</p>
        </div>
    </div>
</div>
{% endblock %}

templates/customer/customer_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Create New Customer
{% endblock title %}

{% block content %}
<h1>Create New Customer</h1>

<form method="post" action="{% url 'customers:customer-create' %}">
    {% csrf_token %} {{ form|crispy }} <button type=" submit" class="btn btn-primary">Create Customer</button>
</form>

{% if form.errors %}
<div class="alert alert-danger">
    Please correct the errors below:
    <ul>
        {% for error in form.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% endblock content %}

templates/customer/customer_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
Customer List
{% endblock title %}
{% block content %}
<h1>Customer List</h1>

<div class="row mb-3">
    <div class="col-md-6">
        <input type="text" id="filter-input" class="form-control"
            placeholder="{% translate 'Filter by name or code' %} ">
    </div>
    <div class="col-md-6 d-flex justify-content-end">
        <button type="button" class="btn btn-primary" id="exportCsvBtn">
            <i class="bi bi-file-earmark-text"></i> Export CSV
        </button>
        <button type="button" class="btn btn-success ms-2" id="importCsvBtn">
            <i class="bi bi-upload"></i> Import CSV
        </button>
        <a href="{% url 'customers:customer-create'%}" class="btn btn-info ms-2">
            <i class="bi bi-plus-circle"></i> Create New Customer
        </a>
    </div>
</div>
{% if customers %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">
                <input type="checkbox" id="select-all" name="customer-checkbox" onclick="selectAllCheckboxes()">
                Select All
            </th>
            <th scope="col">Name</th>
            <th scope="col">Tax ID</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Email</th>
            <th scope="col">Account Balance</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for customer in customers %}
        <tr>
            <td>
                <input type="checkbox" name="customer-checkbox" class="customer-checkbox" value="{{ customer.pk }}">
            </td>
            <td><a href="{% url 'customers:customer-detail' customer.pk %}">{{ customer.name }}</a></td>
            <td>{{ customer.tax_id }}</td>
            <td>{{ customer.phone_number }}</td>
            <td>{{ customer.email }}</td>
            <td>{{ customer.account_balance }}</td>
            <td>
                <a href="{% url 'customers:customer_update' customer.pk %}" class="btn btn-sm btn-info">Edit</a>
                <a href="{% url 'customers:customer-delete' customer.pk %}" class="btn btn-sm btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% for page_num in paginator.page_range %}
        {% if page_num == page_obj.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endif %}
<script>
    function selectAllCheckboxes() {
        // Get the checkbox with id "select-all"
        const selectAllCheckbox = document.getElementById('select-all');
        // Get all checkboxes with class "customer-checkbox"
        const customerCheckboxes = document.querySelectorAll('.customer-checkbox');
        // Loop through each customer checkbox
        customerCheckboxes.forEach(checkbox => {
            // Set the checkbox's checked state to match the "select-all" checkbox
            checkbox.checked = selectAllCheckbox.checked;
        });
    }
    document.getElementById('exportCsvBtn').addEventListener('click', function () {
        // Redirect to the export CSV URL
        window.location.href = "{% url 'customers:export-csv' %}";
    })
</script>


<script>
    document.getElementById('filter-input').addEventListener('keyup', function () {
        // Get the filter input value
        const filterValue = this.value.toUpperCase();

        // Get all the rows in the table
        const rows = document.querySelectorAll('.table tbody tr');

        // Loop through each row
        rows.forEach(row => {
            // Get the name cell
            const nameCell = row.querySelector('td:nth-child(2)');
            const name = nameCell.textContent.toUpperCase();

            // If the name matches the filter, show the row, otherwise hide it
            if (name.indexOf(filterValue) > -1) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
</script>
{% endblock content %}

templates/customer/customer_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Update Customer
{% endblock title %}

{% block content %}
<h1 class="h1">Update Customer</h1>

<form method="post">
    {% csrf_token %} {{ form|crispy }} <button type=" submit" class="btn btn-primary">Update Customer</button>
</form>

{% if form.errors %}
<div class="alert alert-danger">
    Please correct the errors below:
    <ul>
        {% for error in form.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% endblock content %}