COA/urls.py
from django.urls import path
from .views import AccountListView, AccountCreateView,AccountDetailView,AccountUpdateView,AccountDeleteView, export_csv_view,import_csv_view
app_name = 'COA'

urlpatterns = [
    path('accounts/', AccountListView.as_view(), name='account_list'),
    path('accounts/create/', AccountCreateView.as_view(), name='account_create'),
    path('accounts/<int:pk>/', AccountDetailView.as_view(), name='account_detail'),
    path('accounts/<int:pk>/update/', AccountUpdateView.as_view(), name='account_update'),
    path('accounts/<int:pk>/delete/', AccountDeleteView.as_view(), name='account_delete'),
    path('export-csv/', export_csv_view, name='export_csv'),
    path('import-csv/', import_csv_view, name='import_csv'),
]

companyinfo/urls.py
from django.urls import path
from .views import index, create, update, delete


app_name = "companyinfo"

urlpatterns = [
    path("", index, name="index"),
    path("create/", create, name="create"),
    path("update/<int:id>/", update, name="update"),
    path("delete/<int:id>/", delete, name="delete"),
]

customer/urls.py
# customers/urls.py

from django.urls import path
from . import views
from .views import export_csv_view

app_name = 'customers'  # Optional: Namespace for URL names

urlpatterns = [
    path('', views.CustomerListView.as_view(), name='customer-list'),
    path('create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('<str:pk>/', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('<str:pk>/update/', views.CustomerUpdateView.as_view(),
         name='customer_update'),
    path('<str:pk>/delete/', views.CustomerDeleteView.as_view(),
         name='customer-delete'),
    path('export-csv/customers/', export_csv_view, name='export-csv'),
    path('filter/', views.FilterCustomersView.as_view(), name='filter'),

]

htktAcct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [

    path("", include("home.urls")),
    path("coa/", include("COA.urls")),
    path("companyinfo/", include("companyinfo.urls")),
    path("product/", include("product.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/password_reset/",
        PasswordResetView.as_view(
            template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "accounts/login/",
        LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path(
        "accounts/loggout/",
        LogoutView.as_view(template_name="registration/logged_out.html"),
        name="logout",
    ),
    path("admin/", admin.site.urls),
    path('customer/', include('customer.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path
from . import views  # Import views from the same directory (usually)

app_name = 'product'

urlpatterns = [
    # Products
    path('', views.product_list, name='product_list'),  # List all products
    # Detail view for a specific product
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    # Create a new product
    path('add/', views.product_create, name='product_create'),
    path('update/<int:product_id>/', views.product_update,
         name='product_update'),  # Update an existing product
    path('delete/<int:product_id>/', views.product_delete,
         name='product_delete'),  # Delete a product

    # Categories
    path('categories/', views.category_list,
         name='category_list'),  # List all categories
    path('categories/<int:category_id>/', views.category_detail,
         name='category_detail'),  # Detail view for a category
    path('categories/add/', views.category_create,
         name='category_create'),  # Create a new category
    path('categories/update/<int:category_id>/', views.category_update,
         name='category_update'),  # Update a category
    path('categories/delete/<int:category_id>/', views.category_delete,
         name='category_delete'),  # Delete a category

    # Manufacturers
    path('manufacturers/', views.manufacturer_list,
         name='manufacturer_list'),  # List all manufacturers
    path('manufacturers/<int:manufacturer_id>/', views.manufacturer_detail,
         name='manufacturer_detail'),  # Detail view for a manufacturer
    path('manufacturers/add/', views.manufacturer_create,
         name='manufacturer_create'),  # Create a new manufacturer
    path('manufacturers/update/<int:manufacturer_id>/', views.manufacturer_update,
         name='manufacturer_update'),  # Update a manufacturer
    path('manufacturers/delete/<int:manufacturer_id>/', views.manufacturer_delete,
         name='manufacturer_delete'),  # Delete a manufacturer
]

templates/base.html
{% load static %}
{% load i18n %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html>

<head>
    <link rel="icon" type="image/svg" sizes="32x32" href="{% static '/images/logo.svg' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %} ">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"
        integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="{% static 'js/jquery-3.7.1.js' %}"></script>

</head>

<body>
    {% include 'navbar.html' %}
    <div class="container-fluid">
        <!-- Main Content -->
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            {% block content %}
            {% endblock content %}
        </main>
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>

</html>

templates/footer.html
{% load i18n %}
<footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
        <span class="text-muted">
            {% translate 'Your Partner in Business Growth and Financial Management' %} </span>
    </div>
</footer>

templates/navbar.html
{% load i18n %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo.jpg' %}" width="32" height="32" alt="" srcset="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/"> {% trans 'Dashboard' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}"> {% trans 'Invoices' %} </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">{% trans 'Expenses' %} </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">{% trans 'Reports' %} </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {% trans 'Master List' %}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'companyinfo:index' %}">
                                {% trans 'Company Information' %}
                            </a></li>
                        <li><a class="dropdown-item" href="{% url 'COA:account_list' %}">
                                {% trans 'Chart Of Accounts' %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'customers:customer-list' %}">Customers</a></li>
                        <li><a class="dropdown-item" href="{% url 'product:product_list' %}">Product</a></li>
                        <li><a class="dropdown-item" href="{% url 'customers:customer-list' %}">Category</a></li>
                        <li><a class="dropdown-item" href="{% url 'customers:customer-list' %}">Manufacters</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">
                        {% trans 'Logout' %}
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"> {% trans 'Login' %} </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% if user.is_authenticated %}
    <div>
        <img src="{% static 'images/administrator.jpg' %}" width="32" height="32" alt="User avatar">
    </div>
    {% endif %}
</nav>