COA/urls.py
from django.urls import path
from .views import AccountListView, AccountCreateView,AccountDetailView,AccountUpdateView,AccountDeleteView, export_csv_view,import_csv_view
app_name = 'COA'

urlpatterns = [
    path('accounts/', AccountListView.as_view(), name='account_list'),
    path('accounts/create/', AccountCreateView.as_view(), name='account_create'),
    path('accounts/<int:pk>/', AccountDetailView.as_view(), name='account_detail'),
    path('accounts/<int:pk>/update/', AccountUpdateView.as_view(), name='account_update'),
    path('accounts/<int:pk>/delete/', AccountDeleteView.as_view(), name='account_delete'),
    path('export-csv/', export_csv_view, name='export_csv'),
    path('import-csv/', import_csv_view, name='import_csv'),
]

htktAcct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [

    path("", include("home.urls")),
    path("coa/", include("COA.urls")),
    path("companyinfo/", include("companyinfo.urls")),
    path("product/", include("product.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/password_reset/",
        PasswordResetView.as_view(
            template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "accounts/login/",
        LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path(
        "accounts/loggout/",
        LogoutView.as_view(template_name="registration/logged_out.html"),
        name="logout",
    ),
    path("admin/", admin.site.urls),
    path('customer/', include('customer.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

COA/models.py
from decimal import Decimal

import unicodecsv as csv
from django.db import IntegrityError, connection
from django.db import models
from django.http import HttpResponse


# Create your models here.
class Account(models.Model):
    code = models.CharField(max_length=10, primary_key=True, )
    name = models.CharField(max_length=255)
    level = models.PositiveSmallIntegerField(default=0)
    account_type = models.CharField(max_length=20)
    description = models.CharField(
        max_length=255, default=None, null=True, blank=True)
    opening_balance = models.DecimalField(
        max_digits=19, decimal_places=4, default=0)
    debit_only = models.BooleanField(default=True)
    parent_account = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True)
    notes = models.CharField(
        max_length=255, blank=True, null=True, default=None)
    is_original = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.code} - {self.name}'

    @staticmethod
    def export_to_csv():
        response = HttpResponse(content_type='text/csv; charset=utf-8')
        response['Content-Disposition'] = 'attachment; filename="account_data.csv"'

        writer = csv.writer(response, encoding='utf-8-sig')
        writer.writerow(
            ['Code', 'Name', 'Level', 'Account Type', 'Description', 'Opening Balance', 'Debit Only', 'Parent Account',
             'Notes'])

        accounts = Account.objects.all()
        for account in accounts:
            row = [
                account.code,
                account.name,
                account.level,
                account.account_type,
                account.description if account.description else '',
                account.opening_balance,
                account.debit_only,
                account.parent_account_id if account.parent_account else '',
                account.notes,
            ]
            writer.writerow(
                [str(value) if value is not None else '' for value in row])

        return response

    @staticmethod
    def import_from_csv(file):
        # file_data = file.read().decode('utf-8-sig')
        file_data = file.read()
        lines = csv.reader(file_data.splitlines())
        # Skip the header row
        next(lines)
        with connection.cursor() as cursor:
            for fields in lines:
                account_data = dict(
                    code=fields[0],
                    name=fields[1],
                    level=int(fields[2]),
                    account_type=fields[3],
                    description=fields[4] if fields[4] != '\\N' else None,
                    opening_balance=Decimal(fields[5]),
                    debit_only=bool(fields[6]),
                    parent_account_id=fields[7] if fields[7] != '\\N' else None,
                    notes=fields[8] if fields[8] != '\\N' else None,
                )

                query = """
                INSERT INTO coa_account (CODE, NAME, LEVEL, account_type, description, opening_balance, debit_only, parent_account_id, notes)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);
                """
                params = [account_data['code'], account_data['name'], account_data['level'],
                          account_data['account_type'], account_data['description'], account_data['opening_balance'],
                          account_data['debit_only'], account_data['parent_account_id'], account_data['notes']]

                # Print the complete query
                print("Executing query:", cursor.mogrify(query, params))

                try:
                    cursor.execute(query, params)
                # Catch the duplicate key error
                except IntegrityError as e:
                    # Rollback the transaction
                    connection.rollback()
                    # Print the error message
                    print("Error:", e)
                # Skip or update the row as needed
                # For example, you can use cursor.execute("UPDATE ...") to update the existing row
                # Or you can use continue to skip the row and move on to the next one
                continue


class Transaction(models.Model):
    account = models.ForeignKey('Account', on_delete=models.CASCADE)
    opening_balance = models.DecimalField(max_digits=19, decimal_places=4)
    debit_only = models.BooleanField()
    debit_amount = models.DecimalField(max_digits=19, decimal_places=4)
    credit_amount = models.DecimalField(max_digits=19, decimal_places=4)
    closing_balance = models.DecimalField(max_digits=19, decimal_places=4)

    def __str__(self):
        return f"{self.account.name} - {self.debit_amount}/{self.credit_amount}"

COA/forms.py
from django.urls import reverse
from django_filters import FilterSet, CharFilter, ChoiceFilter, BooleanFilter
from .models import Account
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Field, Submit


class UploadFileForm(forms.Form):
    file = forms.FileField()


class AccountFilter(FilterSet):
    # Define the filters for the Account model fields
    # You can use any filter types that suit your needs
    # For example, you can use a CharFilter with a contains lookup for the code and name fields
    # You can use a ChoiceFilter with a list of choices for the level and account_type fields
    # You can use a BooleanFilter for the debit_only field
    code = CharFilter(field_name='code', lookup_expr='icontains')
    name = CharFilter(field_name='name', lookup_expr='icontains')
    level = ChoiceFilter(field_name='level', choices=[
                         (0, '0'), (1, '1'), (2, '2'), (3, '3')])
    account_type = ChoiceFilter(field_name='account_type',
                                choices=[('TÀI SẢN', 'TÀI SẢN'), ('NỢ PHẢI TRẢ', 'NỢ PHẢI TRẢ'),
                                         ('VỐN CHỦ SỞ HỮU',
                                          'VỐN CHỦ SỞ HỮU'), ('DOANH THU', 'DOANH THU'),
                                         ('CHI PHÍ', 'CHI PHÍ')])
    debit_only = BooleanFilter(field_name='debit_only')

    class Meta:
        # Specify the model and the fields to be filtered
        model = Account
        fields = ['code', 'name', 'level', 'account_type', 'debit_only']


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = [
            'parent_account',
            'code',
            'name',
            'level',
            'account_type',
            'description',
            'opening_balance',
            'debit_only',
            'notes']

COA/views.py
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from .models import Account
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.shortcuts import render
from .forms import AccountFilter
from django_filters.views import FilterView
from .forms import AccountForm
from .forms import UploadFileForm
from .models import Account


class AccountListView(LoginRequiredMixin, FilterView):
    model = Account
    template_name = 'coa/account_list.html'
    context_object_name = 'accounts'
    filterset_class = AccountFilter


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = 'coa/account_create.html'
    form_class = AccountForm
    success_url = reverse_lazy('COA:account_list')

    def get_success_url(self):
       # Example: Redirect to the detail page for the created account
        return reverse('COA:account_list', args=[self.object.pk])


class AccountDetailView(LoginRequiredMixin, DetailView):
    model = Account
    template_name = 'coa/account_detail.html'


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = Account
    template_name = 'coa/account_update.html'
    fields = ['code', 'name', 'level', 'account_type', 'description',
              'opening_balance', 'debit_only', 'parent_account']
    success_url = reverse_lazy('COA:account_list')


class AccountDeleteView(LoginRequiredMixin, DeleteView):
    model = Account
    template_name = 'coa/account_delete.html'
    success_url = reverse_lazy('COA:account_list')


def export_csv_view(request):
    return Account.export_to_csv()


def import_csv_view(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['file']
            if not csv_file.name.endswith('.csv'):
                return HttpResponse(status=400, content='Invalid file type')
            Account.import_from_csv(csv_file)
            return HttpResponse(status=200, content='CSV file imported successfully')
    else:
        form = UploadFileForm()
    return render(request, 'COA/import.html', {'form': form})

templates/COA/account_create.html
<!-- templates/coa/account_create.html -->
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Create Account{% endblock %}

{% block content %}
<h1 class="h1">Create Account</h1>
<p>Fill in the details below to create your account:</p>

<form method="post" class="needs-validation" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

  <button type="submit" class="btn btn-primary mt-3">Create</button>
</form>
{% endblock %}

templates/COA/account_delete.html
<!-- account_delete.html -->

{% extends 'base.html' %} <!-- Assuming you have a base template -->

{% block content %}
<h2>Confirm Account Deletion</h2>
<p>Are you sure you want to delete your account?</p>
<p>This action cannot be undone.</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete Account</button>
    <a href="{% url 'COA:account_list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

templates/COA/account_detail.html
{% extends 'base.html' %}
{% load spacefilters %}
{% block title %}
    Chart Of Accounts
{% endblock title %}
{% block content %}
    <h2 class="h2">Okay</h2>
{% endblock  %}

templates/COA/account_list.html
{% extends 'base.html' %}
{% load spacefilters %}
{% block title %}
Chart Of Accounts
{% endblock title %}
{% block content %}
<div class="container ">
    <h1>Account List</h1>
    <div class="row mb-3">
        <div class="col-md-6">
            <input type="text" id="filter-input" class="form-control" placeholder="Filter by name or code">
        </div>
        <div class="col-md-6 d-flex justify-content-end">
            <button type="button" class="btn btn-primary" id="exportCsvBtn">
                <i class="bi bi-file-earmark-text"></i> Export CSV
            </button>
            <button type="button" class="btn btn-success ms-2" id="importCsvBtn">
                <i class="bi bi-upload"></i> Import CSV
            </button>
            <a href="{% url 'COA:account_create' %}" class="btn btn-info ms-2">
                <i class="bi bi-plus-circle"></i> New Account
            </a>
        </div>
    </div>

    <table id="example-table" class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">
                    <input type="checkbox" id="select-all" name="account-checkbox" onclick="selectAllCheckboxes()">
                    Select All
                </th>
                <th scope="col">Code</th>
                <th scope="col">Name</th>
                <th scope="col">Level</th>
                <th scope="col">Account Type</th>
                <th scope="col">Description</th>
                <th scope="col">Opening Balance</th>
                <th scope="col">Debit Only</th>
                <th scope="col">Parent Account</th>
                <th scope="col">Notes</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
            <tr>
                <td>
                    <input type="checkbox" name="account-checkbox" class="account-checkbox" value="{{ account.pk }}">
                </td>
                <td> {{account.code}}</td>
                <td> {{account.name}} </td>
                <td>{{ account.level }}</td>
                <td>{{ account.account_type }}</td>
                <td>{{ account.description | default:'' }}</td>
                <td>{{ account.opening_balance }}</td>
                <td>{{ account.debit_only }}</td>
                <td>{{ account.parent_account | default:'' }}</td>
                <td>{{ account.notes | default:'' }}</td>
                <td>

                    {% if account.is_original == False %}
                    <a href="{% url 'COA:account_detail' account.pk %}" class="btn btn-primary btn-sm"> <i
                            class="fa fa-eye"></i></a>
                    <a href="{% url 'COA:account_update' account.pk %}" class="btn btn-warning btn-sm"><i
                            class="fa fa-pencil"></i></a>
                    <a href="{% url 'COA:account_delete' account.pk %}" class="btn btn-danger btn-sm"> <i
                            class="fa fa-trash"></i></a>
                    {% endif %}


                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



<script>
    document.getElementById('exportCsvBtn').addEventListener('click', function () {
        // Redirect to the export CSV URL
        window.location.href = "{% url 'COA:export_csv' %}";
    });
    document.getElementById('importCsvBtn').addEventListener('click', function () {
        // Redirect to the import CSV URL
        window.location.href = "{% url 'COA:import_csv' %}";
    });
    document.getElementById('newAccountBtn').addEventListener('click', function () {
        // Redirect to the import CSV URL
        window.location.href = "{% url 'COA:account_create' %}";
    });
    // Define a function that filters the table rows by a given value
    function filterTableRows(value) {
        // Convert the value to uppercase
        value = value.toUpperCase();
        // Loop through all the table rows
        $("#example-table > tbody > tr").each(function () {
            // Get the text of all the table cells in the current row
            var rowText = $(this).text().toUpperCase();
            // Check if the row text contains the value
            if (rowText.indexOf(value) > -1) {
                // Show the row
                $(this).show();
            } else {
                // Hide the row
                $(this).hide();
            }
        });
    }
    // Select the input element by id
    var input = $("#filter-input");
    // Attach a keyup event handler to the input element
    input.on("keyup", function () {
        // Get the input value
        var value = input.val();
        // Filter the table rows by the input value
        filterTableRows(value);
    });
</script>
</div>
{% endblock %}

templates/COA/account_update.html
<!-- account_update.html -->
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Update Account</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Save Changes</button>
</form>
<a href="{% url 'COA:account_list' %}">Cancel</a>
{% endblock %}

templates/COA/import.html
{% extends 'base.html' %}
{% block title %}
    Import CSV
{% endblock title %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% endblock %}